import type { ToolMetadata } from '../types';

export const TOOLS: ToolMetadata[] = [
  {
    id: 'image-to-3d',
    name: 'Image to 3D',
    tagline: 'Generate textured 3D meshes from single 2D images',
    description: 'Transform any photo, drawing, or render into a high-fidelity 3D mesh with automatic depth estimation, surface normals, and texture projection.',
    iconName: 'Box',
    badge: 'Core Vision',
    category: '3D & Vision',
    acceptedFormats: ['.png', '.jpg', '.jpeg', '.webp'],
    maxSizeMB: 20,
    outputFormats: ['GLB', 'OBJ', 'STL'],
    isTextBased: false,
  },
  {
    id: 'audio-to-text',
    name: 'Audio to Text',
    tagline: 'Local speech recognition and transcription',
    description: 'Convert voice recordings, interviews, podcasts, and audio clips into clean transcriptions with timestamp markers and subtitle exports.',
    iconName: 'Mic',
    badge: 'Speech-to-Text',
    category: 'Audio & Video',
    acceptedFormats: ['.mp3', '.wav', '.m4a', '.flac', '.ogg'],
    maxSizeMB: 50,
    outputFormats: ['TXT', 'SRT', 'VTT', 'JSON'],
    isTextBased: false,
  },
  {
    id: 'video-to-text',
    name: 'Video to Text',
    tagline: 'Extract audio and transcribe video with subtitles',
    description: 'Process video files locally with FFmpeg audio extraction and Whisper speech-to-text recognition to generate synchronized subtitles.',
    iconName: 'Video',
    badge: 'Video & Subtitles',
    category: 'Audio & Video',
    acceptedFormats: ['.mp4', '.mov', '.mkv', '.webm', '.avi'],
    maxSizeMB: 100,
    outputFormats: ['TXT', 'SRT', 'VTT'],
    isTextBased: false,
  },
  {
    id: 'image-to-text',
    name: 'Image OCR',
    tagline: 'Optical Character Recognition for documents & images',
    description: 'Extract raw text, document layouts, invoices, and signage from images using local optical character recognition engines.',
    iconName: 'FileText',
    badge: 'Vision OCR',
    category: '3D & Vision',
    acceptedFormats: ['.png', '.jpg', '.jpeg', '.webp', '.bmp'],
    maxSizeMB: 15,
    outputFormats: ['TXT', 'JSON'],
    isTextBased: false,
  },
  {
    id: 'summarizer',
    name: 'Smart Summarizer',
    tagline: 'Distill long documents into concise key insights',
    description: 'Summarize articles, research papers, reports, and meeting transcripts locally into executive summaries or structured bullet points.',
    iconName: 'Sparkles',
    badge: 'Local LLM',
    category: 'Language & NLP',
    acceptedFormats: ['.txt', '.md', '.pdf'],
    maxSizeMB: 10,
    outputFormats: ['TXT', 'MD'],
    isTextBased: true,
  },
  {
    id: 'translator',
    name: 'Neural Translator',
    tagline: 'Offline multi-language translation (Nepali ⇄ English)',
    description: 'Translate text accurately between English, Nepali, Hindi, Spanish, French, German, and more with no telemetry or third-party cloud calls.',
    iconName: 'Languages',
    badge: 'Neural MT',
    category: 'Language & NLP',
    acceptedFormats: ['.txt', '.md'],
    maxSizeMB: 5,
    outputFormats: ['TXT'],
    isTextBased: true,
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    tagline: 'Synthesize natural voice in English & Nepali',
    description: 'Generate high quality, natural-sounding audio speech from text with customizable speed, pitch, and voice models entirely on your hardware.',
    iconName: 'Volume2',
    badge: 'Local TTS',
    category: 'Speech',
    acceptedFormats: ['.txt'],
    maxSizeMB: 2,
    outputFormats: ['MP3', 'WAV'],
    isTextBased: true,
  },
];
